version: '2'

services:
 iot-mongo:
  restart: always
  container_name: iot-mongo
  image: mongo:3.4
  #environment:
   #- MONGO_INITDB_ROOT_USERNAME=root
   #- MONGO_INITDB_ROOT_PASSWORD=root
  command: mongod --nojournal --bind_ip 0.0.0.0
  ports:
   - "27017:27017"
  volumes:
   - './mongo_data:/data/db'
  restart: always
 #mongo-iota-manager:
  #container_name: mongo-iota-manager
  #image: mongo:3.4
  #environment:
  # - MONGO_INITDB_ROOT_USERNAME=root
  # - MONGO_INITDB_ROOT_PASSWORD=root
  #command: mongod --nojournal --bind_ip 0.0.0.0 --port 27019
  #ports:
  # - "27019:27019"
  #volumes:
  # - './mongo_data_iota_manager:/data/db'  
 #mongo-iota-ul:
  #container_name: mongo-iota-ul
  #image: mongo:3.4
   #environment:
    #- MONGO_INITDB_ROOT_USERNAME=root
    #- MONGO_INITDB_ROOT_PASSWORD=root
  #command: mongod --nojournal --bind_ip 0.0.0.0 --port 27020
  #ports:
  # - "27020:27020"
  #volumes:
  # - './mongo_data_iota_ul:/data/db' 
 #mongo-iota-json:
  #image: mongo:3.4
  #environment:
   #- MONGO_INITDB_ROOT_USERNAME=root
   #- MONGO_INITDB_ROOT_PASSWORD=root
  #command: mongod --nojournal --bind_ip 0.0.0.0  --port 27021
  #ports:
   #- "27021:27021" 
 orion:
  restart: always
  container_name: orion
  image: fiware/orion
  ports:
   - "1026:1026"
  #command: -dbhost iot-mongo -dbuser root -dbpwd root -logLevel DEBUG
  command: -dbhost iot-mongo -logLevel DEBUG
  #environment:
   #- no_proxy='localhost,172.17.0.4'
  networks:
    - default
  restart: always
 #mosquitto:
  #image: eclipse-mosquitto
  #ports:
   #- "1883:1883"
   #- "9001:9001"
 #iota-ul:
  #container_name: iota-ul
  #image: telefonicaiot/iotagent-ul
  #ports:
  # - "3389:7896"
  # - "9091:4041"
  #environment:
  # - IOTA_CB_HOST=orion
  # - IOTA_CB_PORT=1026
  # - IOTA_PROVIDER_URL='172.17.0.4:4041'
  # - IOTA_MONGO_HOST=mongo-iota-ul
  # - IOTA_MONGO_PORT=27020
  # - IOTA_MQTT_HOST=mosquitto
  # - IOTA_MQTT_PORT=1883
  # - no_proxy='localhost,172.17.0.4,orion,mosquitto'
  #volumes:
  # - './client-config.js:/opt/iotaul/client-config.js'
 #iota-json:
  #image: fiware/iotagent-json
  #ports:
   #- "4042:4042"
  #environment:
   #- IOTA_CB_HOST=orion
   #- IOTA_CB_PORT=1026
   #- IOTA_NORTH_HOST=4042
   #- IOTA_PROVIDER_URL='172.17.0.7:4041'
   #- IOTA_MONGO_HOST=mongo-iota-json
   #- IOTA_MONGO_PORT=27021
   #- IOTA_MQTT_HOST=mosquitto
   #- IOTA_MQTT_PORT=1883
   #- no_proxy='localhost,172.17.0.4,orion,mosquitto'
  #volumes:
   #- './client-config.js:/opt/iotajson/client-config.js'
 #iota-manager:
  #container_name: iota-manager
  #image: telefonicaiot/iotagent-manager
  #ports:
   #- "9090:4040"
  #environment:
  # - IOTA_SERVER_PORT=4040
  # - IOTA_MONGO_HOST=mongo-iota-manager
  # - IOTA_MONGO_PORT=27019
  # - IOTA_LOG_LEVEL=DEBUG
  # - no_proxy='localhost,172.17.0.4,orion,mosquitto,iota-ul,iota-json'
 #idm-keyrock:
  #container_name: idm-keyrock
  #image: fiware/idm
  #ports:
  # - "8000:8000"
  # - "8001:5000"
  #volumes:
  # - './local_settings.py:/horizon/openstack_dashboard/local/local_settings.py'
 #pep-proxy:
  #container_name: pep-proxy
  #image: fiware/pep-proxy
  #ports:
   #- "444:444"
   #- "81:81"
  #volumes:
   #- './config.js:/opt/fiware-pep-proxy/config.js'
 grafana:
  restart: always
  image: grafana/grafana
  container_name: grafana
  depends_on:
   - crate-db
  ports:
   - "3003:3000"
  environment:
   - GF_INSTALL_PLUGINS=crate-datasource,grafana-clock-panel,grafana-worldmap-panel
  user: "420"
  volumes:
   - './grafana:/var/lib/grafana'
  restart: always
 crate-db:
  restart: always
  image: crate:2.3
  hostname: crate-db
  container_name: db-crate
  ports:
   # Admin UI
   - "4200:4200"
   # Transport protocol
   - "4300:4300"
  command: -Ccluster.name=democluster -Chttp.cors.enabled=true -Chttp.cors.allow-origin="*"
  volumes:
   - './crate-db:/data'
  restart: always
 quantum-leap:
  restart: always
  image: smartsdk/quantumleap
  hostname: quantum-leap
  container_name: quantum-leap
  ports:
   - "8668:8668"
  depends_on:
   - crate-db
  environment:
   - CRATE_HOST=crate-db
  restart: always
networks:
 default:
  external:
   name: main_scsk
